export const characterMaster = [
    { "id": "1", "name": "E5 はやぶさくん", "color": "#3fb9b6", "type": "shinkansen" },
    { "id": "2", "name": "E6 こまちちゃん", "color": "#e50012", "type": "shinkansen" },
    { "id": "3", "name": "E7 かがやきくん", "color": "#1c50a1", "type": "shinkansen" },
    { "id": "4", "name": "Dr. イーストアイ", "color": "#cf000e", "type": "shinkansen" },
    { "id": "5", "name": "E3 つばさくん", "color": "#3b1e86", "type": "shinkansen" },
    { "id": "6", "name": "E235 やまのてせんぱい", "color": "#8dc21f", "type": "commuter" },
    { "id": "7", "name": "253 にっこうさん", "color": "#f8bb01", "type": "express" },
    { "id": "8", "name": "251 スーパービューマン", "color": "#2cb3a7", "type": "express" },
    { "id": "9", "name": "E259 ネックスさん", "color": "#e40112", "type": "express" },
    { "id": "10", "name": "E257 あずさくん", "color": "#54579b", "type": "express" },
    { "id": "11", "name": "クレイルさん", "color": "#7e0050", "type": "express" },
    { "id": "12", "name": "E233 けいひんとうほくん", "color": "#00a4de", "type": "commuter" },
    { "id": "13", "name": "E233 なんぶせんせい", "color": "#ee8a01", "type": "commuter" },
    { "id": "14", "name": "E233 しょうなんしんじゅくラビット", "color": "#f08600", "type": "commuter" },
    { "id": "15", "name": "E233 よこはませんちょう", "color": "#009444", "type": "commuter" },
    { "id": "16", "name": "E233 さいきょうまる", "color": "#00a18e", "type": "commuter" },
    { "id": "17", "name": "E233 ちゅうおうせんたいかいそくん", "color": "#e68214", "type": "commuter" },
    { "id": "18", "name": "E231 ちゅうおうせんたいそうぶくん", "color": "#edb619", "type": "commuter" },
    { "id": "19", "name": "E233 とうかいどん", "color": "#00a73b", "type": "commuter" },
    { "id": "20", "name": "E233 けいようくん", "color": "#e50012", "type": "commuter" },
    { "id": "21", "name": "E233 じょうばんさん", "color": "#009d95", "type": "commuter" },
    { "id": "22", "name": "ファステックにゃん", "color": "#f7b400", "type": "cat" },
    { "id": "23", "name": "C61 20 シロクイチさん", "color": "#bb9114", "type": "locomotive" },
    { "id": "24", "name": "D51 498 デゴイチさん", "color": "#bb9114", "type": "locomotive" },
    { "id": "25", "name": "E751 つがるん", "color": "#1d2087", "type": "express" },
    { "id": "26", "name": "E257 わかしおくん", "color": "#fcd12b", "type": "express" },
    { "id": "27", "name": "255 しおさいさん", "color": "#fcd12b", "type": "express" },
    { "id": "28", "name": "253 きぬがわさん", "color": "#f8bb01", "type": "express" },
    { "id": "29", "name": "E653 いなほひめ", "color": "#ec6c00", "type": "express" },
    { "id": "30", "name": "E653 しらゆきおうじ", "color": "#e50012", "type": "express" },
    { "id": "31", "name": "651 スワローあかぎさん", "color": "#fc4f03", "type": "express" },
    { "id": "32", "name": "E657 スーパーフレッシュひたちマン", "color": "#f31c24", "type": "express" },
    { "id": "33", "name": "とれいゆくん", "color": "#006d7b", "type": "shinkansen" },
    { "id": "34", "name": "やまどりちゃん", "color": "#6e4031", "type": "express" },
    { "id": "35", "name": "E353 あずねえさん", "color": "#54579b", "type": "express" },
    { "id": "36", "name": "E353 かいじくん", "color": "#54579b", "type": "express" },
    { "id": "37", "name": "E721 とうほくほんちゃん", "color": "", "type": "commuter" },
    { "id": "38", "name": "205 せんせきせんせい", "color": "", "type": "commuter" },
    { "id": "39", "name": "HB-E210 せんせきとうほくタイガー", "color": "", "type": "cat" },
    { "id": "40", "name": "みのりさん", "color": "", "type": "express" },
    { "id": "41", "name": "フルーティアン", "color": "", "type": "express" },
    { "id": "42", "name": "E3 げんびくん", "color": "#006d7b", "type": "shinkansen" },
    { "id": "43", "name": "しゅくまさん", "color": "", "type": "express" },
    { "id": "44", "name": "C57 180 ばんえつふじん", "color": "#bb9114", "type": "locomotive" },
    { "id": "45", "name": "かいりくん", "color": "", "type": "express" },
    { "id": "46", "name": "E261 サフィールちゃん", "color": "#006787", "type": "commuter" },
    { "id": "47", "name": "E956 アルファXマン", "color": "#2f4663", "type": "shinkansen" },
    { "id": "48", "name": "E257 おどりこちゃん", "color": "#1c96d2", "type": "express" },
    { "id": "49", "name": "E231 むさしのくん", "color": "#e36028", "type": "commuter" },
    { "id": "50", "name": "E235 よこすかそうぶさん", "color": "#036eb7", "type": "commuter" }
    { "id": "51", "name": "GV-E400 あきたさん", "color": "#2d72b8", "type": "commuter" }
    { "id": "52", "name": "GV-E400 にいがたさん", "color": "#e3007f", "type": "commuter" }
    { "id": "53", "name": "E257 しょうなんさん", "color": "#1c96d2", "type": "express" }
    { "id": "54", "name": "E131 ぼうそうさんきょうだい うちぼー", "color": "#fcce00", "type": "commuter" }
    { "id": "55", "name": "E131 ぼうそうさんきょうだい そとぼー", "color": "#fcce00", "type": "commuter" }
    { "id": "56", "name": "E131 ぼうそうさんきょうだい かしま", "color": "#fcce00", "type": "commuter" }
];
